# Generated by Django 5.1.2 on 2024-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_student_profile_pic_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
