# Generated by Django 5.1.2 on 2024-12-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='111', max_length=50, null=True),
        ),
    ]
