# Generated by Django 5.1.2 on 2024-12-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
